### ISSUE TITLE
Suspected copy paste artifact in XRechnung v1.3+ document type identifiers

### ISSUE THREAD

**Issue by bahaabeih** [OpenPEPPOL/edec-codelists#1]
I've just noticed, that published versions of the document types code lists starting from v7.0 upwards have the following artifact, which I doubt is intentional:
Document type identifiers for XRechnung v1.3 and v2.0 end with 16B instead of D16B in the CII version part. Isn't that a mistake?

**Comment by phax** [comment]
Thanks for pointing that out.
Please raise an issue to the Peppol Service Desk.
For 1.3 we don't care (because it never made it), but for 2.0 it is important.
Please reference this issue here.
Thanks!

**Comment by phax** [comment]
Closing this issue, as it is handled in the OpenPeppol issue tracker.
Please report future reports directly via the OpenPeppol Service desk - thanks.
